spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mana
    password: Pass-2018
    url: jdbc:mysql://39.105.126.45:3306/schedule
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.163.com #发送邮件服务器
    username: zhacaiji@163.com #发送邮件的邮箱地址
    password: YXVJGVWFTGPGKOGJ #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 465 #465或者994
    from: zhacaiji@163.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

server:
  port: 4000